### ISSUE TITLE
iOS - WebView - Forms Will Not Submit Using Post Method

### ISSUE THREAD

**Issue by pap5508** [EddyVerbruggen/nativescript-webview-utils#11]
https://github.com/NativeScript/nativescript-angular/issues/1270

**Comment by pap5508** [comment]
@EddyVerbruggen : any suggestion how can i resolved this error ??

**Comment by pap5508** [comment]
@EddyVerbruggen : how can I quick fix it..??

**Comment by pap5508** [comment]
@EddyVerbruggen : any update on this Error ?

**Comment by pap5508** [comment]
@EddyVerbruggen :Any update on this error ??

**Comment by EddyVerbruggen** [comment]
I would have probably responded if that was the case.

**Comment by dgt009** [comment]
Even I’m facing the same issue. What’s the way forward for this issue? Any suggestion?

**Comment by pap5508** [comment]
@EddyVerbruggen : have you worked on this.. ??

**Comment by EddyVerbruggen** [comment]
Noooooo

**Comment by pap5508** [comment]
@EddyVerbruggen : Thank you for your reply. Any plan to work on this issue ? or suggestion to resolve it.. ? I am not able to find it suitable

**Comment by pap5508** [comment]
@EddyVerbruggen : It would be great help if you spend some time to this issue.. ? thanks

**Comment by davecoffin** [comment]
@EddyVerbruggen im happy to fork this and try and fix this bug, but some direction would be appreciated if you have some ideas of why this breaks POST data in webview.

**Comment by davecoffin** [comment]
Ok, I've gotten a little closer but still cant figure out how to add the headers before the request then continue with it. Because what is happening is that on every request, the plugin adds the headers, then discards that request. So the POST request is getting discarded with `decisionHandler(WKNavigationActionPolicy.Cancel);`, then when the new request is evaluated its a GET, not a POST and the data is gone. So navType is `other` instead of `formSubmitted`. So I think we either need to pass the params from the first request to the second, or add the headers before so the normal flow can continue.

@EddyVerbruggen thoughts?
